# printf, printk output to RTT
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n
#CONFIG_SEGGER_RTT_MODE_NO_BLOCK_TRIM=y
#CONFIG_SEGGER_RTT_BUFFER_SIZE_UP=4096
#CONFIG_SEGGER_RTT_SECTION_CUSTOM_DTS_REGION=y